server:
  hostname: mmo.alanchiu.net

  zones:
    - id: zone-0

  wsPort: 5000
  httpPort: 3000

  deployment:
    name: mmo-game-server
    requests:
      cpu: "3"
      memory: "512Mi"
    limits:
      cpu: "3"
      memory: "2Gi"

  autoscaler:
    name: mmo-game-autoscaler
    minReplicas: 1
    maxReplicas: 2

  service:
    name: mmo-game-server-lb

  image:
    repository: alanyau1613/mmo-game-server
    tag: latest
    pullPolicy: Always
