{{- range .Values.server.zones }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.server.service.name }}-{{ .id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: game-server
    zone: {{ .id }}
spec:
  selector:
    app: game-server
    zone: {{ .id }}
    version: {{ coalesce $.Values.server.version $.Values.server.image.tag  }}
  ports:
    - name: ws
      port: {{ $.Values.server.wsPort }}
      targetPort: {{ $.Values.server.wsPort }}
    - name: http
      port: {{ $.Values.server.httpPort }}
      targetPort: {{ $.Values.server.httpPort }}
{{- end }}
