{{- range .Values.server.zones }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: game-server-{{ .id }}
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: default
  hostnames:
    - "{{ $.Values.server.hostname }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/{{ .id }}"
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: ""
      backendRefs:
        - name: {{ $.Values.server.service.name }}-{{ .id }}
          port: {{ $.Values.server.wsPort }}
{{- end }}
